// Generated by CoffeeScript 1.6.3
(function() {
  var Builder, CMD, ClosureCompiler, Server, buildroot, fs, oprtions, root, sys;

  sys = require("sys");

  fs = require("fs");

  Server = require("./node.scripts/Server.js");

  CMD = require("./node.scripts/CMD.js");

  Builder = require("./node.scripts/Build.js");

  ClosureCompiler = require("./node.scripts/ClosureCompiler.js");

  root = "html";

  buildroot = "build";

  ClosureCompiler.setRoot("node.scripts");

  oprtions = {};

  fs.readFile("setting.json", "utf-8", function(err, data) {
    var e, options;
    if (err) {
      sys.log("setting file not found.");
    } else {
      try {
        options = JSON.parse(data);
      } catch (_error) {
        e = _error;
        sys.log('parse error: "setting.json"');
      }
    }
    return Server.create(options.port || 3000, options.host || "localhost", root, function(err, server) {
      if (err) {
        return sys.log(err);
      } else {
        sys.log(server.log());
        server.bindModule(options.scripts || []);
        server.onlog = function(data) {
          console.log(data);
          return sys.log(data.message);
        };
        CMD.append({
          "build": function() {
            Builder.build(options.root || "html", function(err, data) {
              var fd, html, _i, _len, _ref;
              if (err) {
                sys.log("<compile failed>");
                return console.log(err);
              } else {
                sys.log("compile success.");
                _ref = data.html;
                for (_i = 0, _len = _ref.length; _i < _len; _i++) {
                  html = _ref[_i];
                  fd = fs.openSync(buildroot + "/" + html.url, "w");
                  fs.writeSync(fd, html.source, 0, "utf-8");
                  fs.closeSync(fd);
                }
                return sys.log("build success.");
              }
            });
            return "try project building.";
          }
        });
        return CMD.enable();
      }
    });
  });

}).call(this);

/*
//@ sourceMappingURL=app.map
*/
